### ISSUE TITLE
Not getting any photos or Videos

### ISSUE THREAD

**Issue by JonaJoA** [picklepete/pyicloud#108]
Hi Guys,
i am working with this lib for a few days
and i am not getting any photos or videos
the login works great and location as well
but the media is not there :-(

after login i am calling:

albums = api.photos.albums
photos = albums['All Photos'].photos
print("media length : " + str(len(photos)))     -->>> Always 0

on the web i can see the photos 
any suggestions?

**Comment by JonaJoA** [comment]
AND BTW this code is great

**Comment by MikeTheCanuck** [comment]
I just tried your code in a working login session (I'm calling api.contacts methods/properties and I'm getting valid data back, so my "api" object is working at least), and I keep getting 

PyiCloudAPIResponseError: Bad Request (400)

I checked and I have at least one album in iCloud.

The detailed stack trace is here (I hope this helps, though I realize it's not the same issue that you're reporting):

```
---------------------------------------------------------------------------
PyiCloudAPIResponseError                  Traceback (most recent call last)
<ipython-input-31-5b555ba4b586> in <module>()
----> 1 albums = api.photos.albums
      2 #photos = albums['All Photos'].photos
      3 #print("media length : " + str(len(photos)))

/Users/mike/code/pyicloud/pyicloud/services/photos.py in albums(self)
     51     def albums(self):
     52         albums = {}
---> 53         for folder in self._fetch_folders():
     54             if not folder['type'] == 'album':
     55                 # FIXME: Handle subfolders

/Users/mike/code/pyicloud/pyicloud/services/photos.py in _fetch_folders(self, server_ids)
     76             '%s/folders' % self._service_endpoint,
     77             params=self.params,
---> 78             data=data
     79         )
     80         response = request.json()

/Users/mike/code/pyicloud/pyicloud/base.py in request(self, *args, **kwargs)
     97             api_error = PyiCloudAPIResponseError(reason, code)
     98             logger.error(api_error)
---> 99             raise api_error
    100 
    101         return response

PyiCloudAPIResponseError: Bad Request (400)
```

**Comment by JonaJoA** [comment]
Hey there Mike,
i am also getting
contacts & location and account details pretty good

and i am also getting sometimes the same stacktrace error that you shared( 1 of each 5 attempts)

do you have any success receiving photos or videos?

**Comment by MikeTheCanuck** [comment]
Yes - I didn't expect any difference (I figured the 400 error was due to client side issues in the code), but I re-ran your code and just ended up with

`media length : 1`

which is exactly how many photos I currently have in iCloud.

Can you confirm (via icloud.com browsing) that you actually have at least one album?  I had to create one to get past one error, and ultimately so that the code would work for me correctly.

**Comment by JonaJoA** [comment]
OK
so i have more info about this issue

i created a test account : 
appleId : JonaJoTest@gmail.com

i added 2 photos 
run this code

       
        from pyicloud import PyiCloudService
        api = PyiCloudService("jonajotest@gmail.com", "*********")
    
        print("Fetching photos")
        photosFolder = 'backup\\photos'
        if not os.path.exists(photosFolder):
            os.makedirs(photosFolder)
        
        albums = api.photos.albums

        photos = albums['All Photos'].photos
        print("media length : " + str(len(photos)))
        for photo in photos:
            print('downloading : ' + photo.data['details']['filename'] + " , FileSize:" + str(photo.data['details']['filesize']))

            download = photo.download()                
            with open(photosFolder + '\\' + photo.filename, 'wb') as opened_file:
                opened_file.write(download.raw.read())

 and the good result was:

Fetching photos and videos
media length : 2
downloading : IMG_0001.JPG , FileSize:1782207
downloading : IMG_6241.JPG , FileSize:116220

Well what can i say ... i was very happy at this point :-)

BUT then i added new image 
i ran the followed code again and keep getting only 2 images ......
why is this happens ?
i tried to remove all the cookies but with no help

what do you think?
if you want i can give you the password for test this account

**Comment by JonaJoA** [comment]
OK
So guys finally i got it
what happens was that there was an open issue on oct 10
 and an open pull request 
https://github.com/picklepete/pyicloud/pull/100

suddenly my problem looked like the one that "torarnv" the great solved
so i took this branch because for some reason its not in the main branch

AND everything works smoothly!!!!
HAPPINESS
so after taking the following branch all i had to do is:

calling this code:


        albums = api.photos.albums
        photos = albums['All Photos'].photos
        print("media length : " + str(len(photos)))      #still old number

        update = api.photos.update()
        print("Update returned : " + str(update))

        albums = api.photos.albums
        photos = albums['All Photos'].photos
        print("media length : " + str(len(photos)))     #GOOD 

I hope it helps anyone 
Thanks
