### ISSUE TITLE
Keep getting api_error LOCKED when updating photos 

### ISSUE THREAD

**Issue by JonaJoA** [picklepete/pyicloud#109]
Hi guys,
i am doing a fetch on location contacts and the photos folder
i am getting all correctly but the photos

does anyone is getting this error:

```shell
<class 'pyicloud.exceptions.PyiCloudAPIResponseError'>
('Locked (423)',)

Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pyicloud-0.9.1-py3.6.egg\pyicloud\cmdline.py", line 120, in fetchingLastPhotos
    albums = api.photos.albums

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pyicloud-0.9.1-py3.6.egg\pyicloud\services\photos.py", line 54, in albums
    self._update_folders()

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pyicloud-0.9.1-py3.6.egg\pyicloud\services\photos.py", line 73, in _update_folders
    data=data

  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\pyicloud-0.9.1-py3.6.egg\pyicloud\base.py", line 192, in request
    raise api_error

pyicloud.exceptions.PyiCloudAPIResponseError: Locked (423)
```

any suggestions?

**Comment by JonaJoA** [comment]
My code is running each 1 Hour


Code:


    from pyicloud import PyiCloudService
    api = PyiCloudService("adamnoamporat@icloud.com", "Kidos2016")

    mediaFrom = 0
    print("Media from : " + str(mediaFrom))
    if mediaFrom is not -1:
        print("Fetching photos and videos")
        photosFolder = outputFolder + '\\photos'
        videosFolder = outputFolder + '\\videos'
        if not os.path.exists(photosFolder):
            os.makedirs(photosFolder)
        if not os.path.exists(videosFolder):
            os.makedirs(videosFolder)

        albums = api.photos.albums

        photos = albums['All Photos'].photos
        print("media length : " + str(len(photos)))
        for photo in photos:
            if photo.data['createdDate'] > mediaFrom:
                photoDataJson = json.dumps(photo.data, ensure_ascii=False)
                print('downloading : ' + photo.data['details']['filename'] + " , FileSize:" + str(photo.data['details']['filesize']))

                download = photo.download()
                if photo.data['type'] == 'image':
                    with open(photosFolder + '\\' + photo.filename, 'wb') as opened_file:
                        opened_file.write(download.raw.read())

                    videoInfo = photoDataJson
                    with open(photosFolder + '\\' + photo.filename + '.info', 'w') as opened_file:
                        opened_file.write(videoInfo)
                elif photo.data['type'] == 'video':
                    with open(videosFolder + '\\' + photo.filename, 'wb') as opened_file:
                        opened_file.write(download.raw.read())

                    videoInfo = photoDataJson
                    with open(videosFolder + '\\' + photo.filename + '.info', 'w') as opened_file:
                        opened_file.write(videoInfo)
`

**Comment by JonaJoA** [comment]
My Code is running every 1 Hour

the Code:

    def fetchingLastPhotos(api, mediaFrom, outputFolder):
    try:
        print("Media from : " + str(mediaFrom))
        if mediaFrom is not -1:
            print("Fetching photos and videos")
            photosFolder = outputFolder + '\\photos'
            videosFolder = outputFolder + '\\videos'
            if not os.path.exists(photosFolder):
                os.makedirs(photosFolder)
            if not os.path.exists(videosFolder):
                os.makedirs(videosFolder)

            albums = api.photos.albums
            photos = albums['All Photos'].photos

            update = api.photos.update()
            print("Update returned : " + str(update))
            print("media length : " + str(len(photos)))

            for photo in photos:
                if photo.data['createdDate'] > mediaFrom:
                    photoDataJson = json.dumps(photo.data, ensure_ascii=False)
                    print('downloading : ' + photo.data['details']['filename'] + " , FileSize:" + str(
                        photo.data['details']['filesize']))

                    download = photo.download()
                    if photo.data['type'] == 'image':
                        with open(photosFolder + '\\' + photo.filename, 'wb') as opened_file:
                            opened_file.write(download.raw.read())

                        videoInfo = photoDataJson
                        with open(photosFolder + '\\' + photo.filename + '.info', 'w') as opened_file:
                            opened_file.write(videoInfo)
                    elif photo.data['type'] == 'video':
                        with open(videosFolder + '\\' + photo.filename, 'wb') as opened_file:
                            opened_file.write(download.raw.read())

                        videoInfo = photoDataJson
                        with open(videosFolder + '\\' + photo.filename + '.info', 'w') as opened_file:
                            opened_file.write(videoInfo)
    except Exception as inst:
        print(type(inst))  # the exception instance
        print(inst.args)
        traceback.print_exc()

**Comment by torarnv** [comment]
Never seen `Locked (423)` returned before. Does it correspond with anything you're doing with other iCloud Photo clients?

**Comment by torarnv** [comment]
I've seen this a few times now, could be you have to throttle the API access? Everything worked if I just waited a bit.

**Comment by JonaJoA** [comment]
Hi there Torarnv,

sorry for not responding i was on VACA 

i am still getting this error 
my guess is that there is some code that is not thread safe
maybe something with the writing to the cookie jar

i am also using this code to fetch 3 accounts and not 1 
sometimes it works (about 15% of the times)

what do you think?

**Comment by Thamster** [comment]
Saw this issue too when fetching photos for an account every minute with a cron job, switched cron job to once an hour and it went away.

**Comment by torarnv** [comment]
https://github.com/picklepete/pyicloud/pull/137 has landed, please verify if this still is an issue

**Comment by Quentame** [comment]
Closing the issue because staled.

But feel free to comment if still the case after updating.
