### ISSUE TITLE
Reincubate project - any ideas worth sharing?

### ISSUE THREAD

**Issue by MikeTheCanuck** [picklepete/pyicloud#111]
Here's a project I stumbled across while looking for ideas on how to submit writes to iCloud data - the Reincubate project:
https://github.com/reincubate/ricloud

It's licensed under LGPL v3, which I'm not terribly familiar with, but if the license permits it, I'd certainly encourage reading the code for any design ideas that could be borrowed (e.g. the way they implement interactive authentication especially the user messaging), and/or any code itself that might be useful.

If the license doesn't permit this kind of sharing, or not without conflicting with the existing MIT license, I surely won't be offended if you close this issue immediately.

**Comment by torarnv** [comment]
Interesting project. The `ricloud` project on GitHub is just a thin wrapper around their REST iCloud API though (which is closed source), so nothing to share unfortunately 🙁 

As a side-note, the Reincubate iCloud API product page doesn't say anything about cost, and I'd also be weary about going through a third-party for both auth and data extraction.

**Comment by MikeTheCanuck** [comment]
Yes, hell no I didn't intend for this project to (a) require any paid dependencies or (b) use a third-party for any of the operations of the package.  Thanks for looking into it!
