### ISSUE TITLE
Any ideas on the following error?

### ISSUE THREAD

**Issue by NathanWilcox** [picklepete/pyicloud#117]
I have installed the service, I now try
`api = PyiCloudService('myaccount@icloud.com','password')`
with my credentials and it returns:

> -bash: syntax error near unexpected token `('

so proceeded to remove the "(" and ")" from the command so no looks like:
`api = PyiCloudService'myaccount@icloud.com','password'`
again with my credentials and this returns:

> -bash: api: command not found

I'm lost.

FYI i'm using http://jtkdev.com/wp/2016/02/06/iphone-locator-for-openhab/ as my guide.

**Comment by torarnv** [comment]
`pyicloud` is a Python API, you have to write a python script or use the python interpreter to execute these commands:

```
$ python
Python 2.7.11 (default, Jan  7 2016, 16:03:47)
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 2 + 2
4
```
