### ISSUE TITLE
Could not to get images from icloud for above iphone 6

### ISSUE THREAD

**Issue by egrovepythondev** [picklepete/pyicloud#119]
I can only get images below iphone 6S version. I could not to get above all iphone 6+.

**Comment by torarnv** [comment]
Can someone confirm? I don't have access to these devices.

**Comment by cvpe** [comment]
See [here](https://github.com/picklepete/pyicloud/issues/85)

**Comment by torarnv** [comment]
Please check if https://github.com/picklepete/pyicloud/pull/137 fixes the issue.

**Comment by Quentame** [comment]
No response, gone stale.

Please create a new issue if still exists.
