### ISSUE TITLE
3 month older images only available.

### ISSUE THREAD

**Issue by egrovepythondev** [picklepete/pyicloud#120]
Three month older images only available. Could not to get recent images

**Comment by numshub** [comment]
Same issue here. I can access all photos up to 31-12-2016. All newer photos are visible in iCloud.com but cannot be retrieved with pyicloud.

**Comment by cvpe** [comment]
See [here](https://github.com/picklepete/pyicloud/issues/85)

**Comment by dimiebr** [comment]
I have de same issue.
Only photos at 31-12-2016.
https://github.com/ndbroadbent/icloud_photos_downloader

**Comment by cvpe** [comment]
I have had to
- modify pyicloud/services/Photos.py to add def update
Like described here [here](https://github.com/picklepete/pyicloud/issues/85)
- insert 	update = api.photos.update() # to bypass a bug of recent photos not seen
Just after getting all photos
	albums = api.photos.albums
	photos = albums['All Photos'].photos
	update = api.photos.update() # to bypass a bug of recent photos not seen

**Comment by numshub** [comment]
This worked for me too. Thanks a lot for the hint.

**Comment by ndbroadbent** [comment]
There is a pull-request that will fix this: #100

For now, you can install the fixed version by running this command:

    sudo pip install git+https://github.com/torarnv/pyicloud.git@photos-update

**Comment by torarnv** [comment]
Please check if https://github.com/picklepete/pyicloud/pull/137 fixes the issue

**Comment by Quentame** [comment]
No response, gone stale.
