### ISSUE TITLE
Use proxy to connect to iColud

### ISSUE THREAD

**Issue by JeffreyFish** [picklepete/pyicloud#126]
Hi,
Can I use HTTP proxy to connect to iColud via pyicloud? If yes, how to do?

**Comment by torarnv** [comment]
```
$ export HTTP_PROXY="http://10.10.1.10:3128"
$ export HTTPS_PROXY="http://10.10.1.10:1080"
```

http://stackoverflow.com/questions/8287628/proxies-with-python-requests-module

http://docs.python-requests.org/en/master/user/advanced/
