### ISSUE TITLE
calendar.events fails with "JSONDecodeError: Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by strycker** [picklepete/pyicloud#141]
When attempting to access my calendar events, the events() command fails with the following error:

api.calendar.events()

---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-71-869053a8e625> in <module>()
----> 1 myAppleCalendarApi.calendar.events()

/home/gstrycker/anaconda3/lib/python3.6/site-packages/pyicloud/services/calendar.py in events(self, from_dt, to_dt)
     59         Retrieves events for a given date range, by default, this month.
     60         """
---> 61         self.refresh_client(from_dt, to_dt)
     62         return self.response['Event']

/home/gstrycker/anaconda3/lib/python3.6/site-packages/pyicloud/services/calendar.py in refresh_client(self, from_dt, to_dt)
     53         })
     54         req = self.session.get(self._calendar_refresh_url, params=params)
---> 55         self.response = req.json()
     56 
     57     def events(self, from_dt=None, to_dt=None):

/home/gstrycker/anaconda3/lib/python3.6/site-packages/requests/models.py in json(self, **kwargs)
    795                     # used.
    796                     pass
--> 797         return json.loads(self.text, **kwargs)
    798 
    799     @property

/home/gstrycker/anaconda3/lib/python3.6/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    352             parse_int is None and parse_float is None and
    353             parse_constant is None and object_pairs_hook is None and not kw):
--> 354         return _default_decoder.decode(s)
    355     if cls is None:
    356         cls = JSONDecoder

/home/gstrycker/anaconda3/lib/python3.6/json/decoder.py in decode(self, s, _w)
    340         end = _w(s, end).end()
    341         if end != len(s):
--> 342             raise JSONDecodeError("Extra data", s, end)
    343         return obj
    344 

JSONDecodeError: Extra data: line 1 column 5 (char 4)

**Comment by strycker** [comment]
UPDATE:  I'm doing some digging and attempting to call the API directly using the session class.

api.calendar.session.get(api.calendar._calendar_refresh_url)



---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-57-2caa6f64a22f> in <module>()
----> 1 myAppleCalendarApi.calendar.session.get(myAppleCalendarApi.calendar._calendar_refresh_url)

/home/gstrycker/anaconda3/lib/python3.6/site-packages/requests/sessions.py in get(self, url, **kwargs)
    471 
    472         kwargs.setdefault('allow_redirects', True)
--> 473         return self.request('GET', url, **kwargs)
    474 
    475     def options(self, url, **kwargs):

/home/gstrycker/anaconda3/lib/python3.6/site-packages/pyicloud/base.py in request(self, *args, **kwargs)
     59         callee = inspect.stack()[2]
     60         module = inspect.getmodule(callee[0])
---> 61         logger = logging.getLogger(module.__name__).getChild('http')
     62         if self.service._password_filter not in logger.filters:
     63             logger.addFilter(self.service._password_filter)

AttributeError: 'NoneType' object has no attribute '__name__'

**Comment by PythonicCoder101** [comment]
This solves the issue it worked for me: 
api.authenticate()

**Comment by Quentame** [comment]
Seems to have the solution in #166.

Please create a new issue if still exists.
