### ISSUE TITLE
Calendar pGuid Titles

### ISSUE THREAD

**Issue by mittermayr** [picklepete/pyicloud#15]
Do you see a possibility to add some sort of function that allows extracting/converting the pGuid from an event to its calendar name?

I have a calendar pGuid like this:
7502832C-B9C6-4218-BC61-03594630219A

And the calendar is called:
"Flights"

It returns the proper name for "home" in pGuid, but not for the other calendars. I tried to look it up myself, but wasn't sure which API you were using there, couldn't find anything over at Apple.

**Comment by torarnv** [comment]
Do you still need this? iCloud has an endpoint that lets us resolve this easily (the startup endpoint) but it would probably mean also massaging CalendarService to be a bit more like the other services in terms of how properties are accessed, so it's more work than just a on-line request.

**Comment by mittermayr** [comment]
I personally don't (moved on to a different project) — but anyone working with multiple calendars (and surfacing their names in some form of UI) will likely need this. Perhaps wait and see if anyone else comments here to have this looked at in the near future.

**Comment by sunnysmith** [comment]
This would be very handy.  Maybe a method to get the list of calendars and the be able to query just that calendar.  Or at a minimum, have the calendar name.  I have 8 calendars and many of the events are not what I want.  I was looking at a filter by etag but that is messy.

**Comment by felciano** [comment]
+1

**Comment by Quentame** [comment]
I don't get what you want to add, sorting events ?, calendars ? by name ? by date ?

Is #178 fixing ?

Thanks

**Comment by Quentame** [comment]
Stale issue

**Comment by Quentame** [comment]
Maybe this can help to propose a PR : https://github.com/MauriceConrad/iCloud-API/commit/c284671afef4cd2678574e42c2aad8e7cce9d92d
