### ISSUE TITLE
There seems to be a new two-step authentication now

### ISSUE THREAD

**Issue by stan-chen** [picklepete/pyicloud#150]
ICloud now seems to have become the default two certification, when the first login two authentication will directly send verification code to the default iPhone, the default will not allow the user to choose which way two certification, so now API only list the equipment SMS.

**Comment by torarnv** [comment]
I'm sorry, I don't understand your message. Could you try rephrasing it?

**Comment by chenxuefei-pp** [comment]
Sorry for my english skill....show you the code
```
api = PyiCloudService('chenxuefei_pp@163.com', 'Cxf53684051')
if api.requires_2sa:
    import click
    print("Two-step authentication required. Your trusted devices are:")
    devices = api.trusted_devices
    for i, device in enumerate(devices):
        print("%s: %s" % (i, device.get('deviceName',"SMS to %s" % device.get('phoneNumber'))) )

    device = click.prompt('Which device would you like to use?', default=0)
    device = devices[device]
    if not api.send_verification_code(device):
        print("Failed to send verification code")
        sys.exit(1)  
```
The code will output:
```
Two-step authentication required. Your trusted devices are:
0: SMS to *********12
Which device would you like to use? [0]: 
```
Only one device is shown here.
My iPhone Received a validation code when I haven't input code yet.
I think iCloud send the validation code to default device when call auth() the first time.

**Comment by hobarrera** [comment]
I'll help rephrase a bit here, since @chenxuefei-pp seems to be running into the same issue I am.

This library seems to prompt a user to select a device to receive an SMS. Currently, this does not work; when trying to log in, my iPhone immediately shows me a screen with a token to use as a second factor.

I've only used iPhones for about 2 years, and I've never come across the SMS variant. Their docs say that it's pre-iOS9, so it's possible that newer devices were never capable of using the SMS variant (2SA, rather than 2FA).

**Comment by chenxuefei-pp** [comment]
@hobarrera  I tried transmit a empty dict to `validate_verification_code()` like this:
```
code = click.prompt('Please enter validation code')
if not api.validate_verification_code(dict(), code):
    print("Failed to verify verification code")
    sys.exit(1)
```
seems can work.

**Comment by WhyNotHugo** [comment]
Huh, neat, that worked! 🎉

**Comment by grokkingStuff** [comment]
This needs to be updated in the example code. Currently works for me.

**Comment by Quentame** [comment]
Working perfectly with the new version in 2020 with an iPhone 11 (iOS 13+) & MacBook Pro 2018 (macOS 10.15).

Closing the issue.
