### ISSUE TITLE
 certificate verify failed

### ISSUE THREAD

**Issue by Aadit-Bhojgi** [picklepete/pyicloud#153]
I have been using the module for quite some time but today when i ran it, it is giving me the following error:
`requests.exceptions.SSLError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=17DHotfix5&clientMasteringNumber=17DHotfix5&clientId=***(Id is masked)&ckjsVersion=2.0.5&ckjsBuildVersion=17DProjectDev77 (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))`
Does anyone else facing this problem??
@torarnv  @chadj

**Comment by chadj** [comment]
This is consistently happening for you?  I’ll try to duplicate later today.

**Comment by Aadit-Bhojgi** [comment]
It is used to be working flawlessly before.
But when i tried running it today it is showing me this error everytime i try to run it.
What is the issue by the way, I don't know what is happening?
@chadj

**Comment by chadj** [comment]
I'm not able to reproduce this problem on my end.  Can you try updating the "requests" module.  If that fails try installing (or updating) the "pyOpenSSL" and "idna" modules.

**Comment by Aadit-Bhojgi** [comment]
Made some changes to my system and updated some modules(like pyOpenSSL) it is working fine now.
Thank you, @chadj

**Comment by Aadit-Bhojgi** [comment]
Made some changes to my system and updated some modules(like pyOpenSSL) it is working fine now.
Thank you, @chadj
