### ISSUE TITLE
Add support for iCloud Notes

### ISSUE THREAD

**Issue by wangsijie** [picklepete/pyicloud#173]

**Comment by gradywoodruff** [comment]
is it possible to access the notes through the iCloud files?

**Comment by wangsijie** [comment]
@gradywoodruff It seems possible to access the notes DIRECTLY through iCloud web.

**Comment by gradywoodruff** [comment]
I mean accessing the contents of Notes on the iOS notes program through this API

**Comment by GitHub30** [comment]
like this ? #87

**Comment by wangsijie** [comment]
> like this ? #87

exactly

**Comment by mouss-delta** [comment]
So is it possible to access iCloud Notes?

**Comment by mouss-delta** [comment]
For me it doesn't work for iCloud Notes. When I type api.files.dir(), there is no u'com~apple~Notes'. Do I have to configure something in my iClound account?

**Comment by wangsijie** [comment]
> For me it doesn't work for iCloud Notes. When I type api.files.dir(), there is no u'comappleNotes'. Do I have to configure something in my iClound account?

NO，this issue is a feature request and no response yet.

**Comment by mouss-delta** [comment]
@torarnv @picklepete I would like to contribute to add notes support. I have looked at the code, basically it consists in :
1. POST request with account info to https://setup.icloud.com/setup/ws/1/login. This webservice returns à JSON. This JSON contains a lot of attribut and especially `webservices` : 
`"webservices": {
"reminders": {
"url": "https://p14-remindersws.icloud.com:443",
"status": "active"
},
"ckdatabasews": {
"pcsRequired": true,
"url": "https://p14-ckdatabasews.icloud.com:443",
"status": "active"
},
"photosupload": {
"pcsRequired": true,
"url": "https://p14-uploadphotosws.icloud.com:443",
"status": "active"
},
"photos": {
"pcsRequired": true,
"uploadUrl": "https://p14-uploadphotosws.icloud.com:443",
"url": "https://p14-photosws.icloud.com:443",
"status": "active"
},...
"findme": {
"url": "https://p14-fmipweb.icloud.com:443",
"status": "active"
},
"calendar": {
"url": "https://p14-calendarws.icloud.com:443",
"status": "active"
}, ...., 
"ubiquity": {
"url": "https://p14-ubiquityws.icloud.com:443",
"status": "active"
}`
2. Wrapping the `webservices` JSON into python services. For exemple `UbiquityService` wraps `ubiquity` attribut of `webservices` JSON,  as well as `CalendarService` with `calendar`, `ContactsService` with `contacts`, etc....
3. Then when in python we do for instance `api.reminders` you make a GET request to associated URL `https://p14-remindersws.icloud.com:443` to get the data. 

=> **My question is simple**, which attribute of `webservices` JSON should I wrap in a `NotesService` that would give the feature of accessing iCloud Notes.

**Comment by landall** [comment]
> For me it doesn't work for iCloud Notes. When I type api.files.dir(), there is no u'com~apple~Notes'. Do I have to configure something in my iClound account?

If you upgrade you iCloud through iOS upgrade, you may get this result as i guess.

**Comment by landall** [comment]
A hint about iCloud Notes through drivews service.
The SnippetEncrypted, TitleEncrypted field can be decoded as base64.
The TextDataEncrypted field should be decoded by three steps:
1. base64 decode
2. zlib decode(I use zlib_decode() in php)
3. protobuf decode

**Comment by zarkin404** [comment]
[pyicloud.zip](https://github.com/picklepete/pyicloud/files/7775084/pyicloud.zip)

I have finished a simple demo to fetch all notes inspired by @MauriceConrad 's project [iCloud-API](https://github.com/MauriceConrad/iCloud-API)

You can use the following code to get the notes:

```
    api = PyiCloudService(username, password)
    for note in api.notes.records:
        print(note["fields"]["Text"])
```

I just changed `base.py`, and added `services/notes.py`, `protobuf` to added this feature.

Hope you guys like it.
