### ISSUE TITLE
How to capture pyicloud URL requests via Charles?

### ISSUE THREAD

**Issue by northtree** [picklepete/pyicloud#177]
I am developing some features based on pyicloud. And I used Charles to capture the requests. I had already setup the SSL certificate which enables Charles to show HTTPS content (e.g it works on https://google.com). 

However, it doesn't work on https://setup.icloud.com. It said that _'Client SSL handshake failed: CA certificate could not be matched with a known, trusted CA (unknown_ca)'_. 

From pyicould, I got this error.

> requests.exceptions.SSLError: HTTPSConnectionPool(host='setup.icloud.com', port=443): Max retries exceeded with url: /setup/ws/1/login?clientBuildNumber=***** (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833)'),))

BTW, I could capture icloud.com by Chrome (under Charles proxy).

**Comment by airwolf2026** [comment]
try disable ssl verify ?

**Comment by northtree** [comment]
@airwolf2026 Could I know how to disable and still fetch the content?

**Comment by airwolf2026** [comment]
@northtree Sorry come later.
In PyiCloudService class's __init__fun set the default arg 'verify' =False
 self.session.verify = verify
Only set this ,the request session will warnning you no secure request ,you can disable the warnning
by set a global vars,sorry forget that arg name
may help

**Comment by Quentame** [comment]
@northtree 
Is your issue was solved ?

Not a library issue, closing
