### ISSUE TITLE
Issues with pull request

### ISSUE THREAD

**Issue by maciejbuchert** [picklepete/pyicloud#179]
Hey @picklepete can you add function that I tried to pull request here https://github.com/picklepete/pyicloud/pull/178 ?

I need it ASAP :/

**Comment by coddingtonbear** [comment]
It looks like you have some problems in your added code over there on #178, @maciejbuchert; I'm afraid you'd have to fix those before we could merge your PR.  Let's continue this conversation on #178 instead of here.
