### ISSUE TITLE
Will this code work iOS 11.4 iCloud 2-factor-authorization system?

### ISSUE THREAD

**Issue by oct-test** [picklepete/pyicloud#183]
I want to try the pyicloud plugin but before I start, I wanted to check if this code works with iOS 11.4 iCloud 2FA authorization system?

Thank you.

**Comment by zzeleznick** [comment]
Tested this today against my PR #160 and works with 2FA on iOS 11.3.

**Comment by Quentame** [comment]
What code ?

This library is working with iOS 12 + 13 (tested by me, but even lower by the owner), so it should work with 11.

Not an issue.
