### ISSUE TITLE
Can I get banned with this?

### ISSUE THREAD

**Issue by zefoo** [picklepete/pyicloud#196]
Anyone happen to know if you could get banned using this library? eg. to use things like pulling a Photos or Find My Friends? I realize it simply logs into the web interface so I doubt it... wondering if anyone has heard of such a thing.

**Comment by dsouzarc** [comment]
I haven't heard of it but I would definitely exercise caution with the polling frequency - something in the range of every 30ish minutes with some time off

**Comment by zzeleznick** [comment]
Taking a page from `reincubate`: https://docs.reincubate.com/ricloud/icloud-account-locking/

<img width="723" alt="screen shot 2018-12-12 at 1 54 31 pm" src="https://user-images.githubusercontent.com/5779832/49901241-81306180-fe15-11e8-8794-ec5e65e76043.png">

**Comment by arjannv** [comment]
I'm requesting the FindMyIphone location of me and my family every 10 minutes for about a year now. Not yet received a ban fortunately

**Comment by dsouzarc** [comment]
@arjannv That's pretty frequent - have you/anyone in your family noticed any effect on battery life?

**Comment by Quentame** [comment]
Used the lib for more than a year now, and not banned.

Closing.
