### ISSUE TITLE
Release 0.9.2 ?

### ISSUE THREAD

**Issue by kdvlr** [picklepete/pyicloud#198]
Is there a newer release of pyicloud on pip? This would be useful for projects such as homeassistant that utilize this code.

**Comment by fantapop** [comment]
@coddingtonbear Any chance for one last release of this?  There has been a lot of great fixes sitting around unused for a few years now.

**Comment by coddingtonbear** [comment]
Oh, hrm; I hadn't noticed that this project had run out of active maintainers -- I haven't been involved in a couple years now.  I do, though, have the ability to do releases, still, and have just released 0.9.2 including what is currently in master.

**Comment by Quentame** [comment]
Thanks @coddingtonbear 

If you wich I can continue to maintain the library, if you give me the rights.

**Comment by Quentame** [comment]
@fantapop I will update Home Assistant

**Comment by coddingtonbear** [comment]
I'm afraid I don't have quite the level of access necessary to do that!  How would you feel about that, though, @picklepete?
