### ISSUE TITLE
AttributeError: 'PyiCloudService' object has no attribute 'requires_2sa'

### ISSUE THREAD

**Issue by Suncatcher** [picklepete/pyicloud#199]
I installed pyicloud using pip3 and trying to run my script using IDLE interactive shell like this:

    exec(open("script.py").read())

It throws this error

	>>> exec(open("script.py").read())
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "<string>", line 5, in <module>
	AttributeError: 'PyiCloudService' object has no attribute 'requires_2sa'

Here is the script:

	from pyicloud import PyiCloudService

	api = PyiCloudService('member@icloud.com', 'pass')

	if api.requires_2sa:
		import click
		print("Two-step authentication required. Your trusted devices are:")

		devices = api.trusted_devices
		for i, device in enumerate(devices):
			print("  %s: %s" % (i, device.get('deviceName',
				"SMS to %s" % device.get('phoneNumber'))))

		device = click.prompt('Which device would you like to use?', default=0)
		device = devices[device]
		if not api.send_verification_code(device):
			print("Failed to send verification code")
			sys.exit(1)

		code = click.prompt('Please enter validation code')
		if not api.validate_verification_code(device, code):
			print("Failed to verify verification code")
			sys.exit(1)

	api.photos.all

Any suggestions? I am using Python 3.6.7.

**Comment by hairychris** [comment]
```
if api.requires_2sa:
```

Should read

```
if api.requires_2fa:
```

There is a typo in the README file

**Comment by Quentame** [comment]
Closed after 69af919ad552b6a0ff5dfe14b81e59f7f2861577
