### ISSUE TITLE
Download data from iclod

### ISSUE THREAD

**Issue by vipinbeni** [picklepete/pyicloud#20]
Hi Sir, 

Please tell me how can i download  data from icloud using ubiquity.py as  i am able to run Find my iphone command line tool options  but not able to use File Storage  option please help 

i install setup.py and it generate icloud .exe which show option only for  Find my iphone command line tool so please help me 

as i not know much about python.

thanks

**Comment by torarnv** [comment]
The command line tool does not provide the functionality to download iCloud data, you'll have to use the API directly for that.
