### ISSUE TITLE
Error in Calendar when no event

### ISSUE THREAD

**Issue by iDustbin** [picklepete/pyicloud#219]
Hi, 

```python
gps_location = api.iphone.location()
print gps_location

phone_status = api.iphone.status()
print phone_status

api.calendar.events()
```

```shell
File "test.py", line 37, in <module>
    api.calendar.events()
  File "/Users/idustbin/pyicloud/pyicloud/services/calendar.py", line 63, in events
    return self.response['Event']
KeyError: 'Event'
```

**Comment by DgRosa** [comment]
@iDustbin this issue happened to me too and I figured it out, it's because no events are found. Make sure you have events in you calendars.

**Comment by Quentame** [comment]
Hi @iDustbin !

Was it what @DgRosa said ?
If so we should provide a fix to return an empty list.

Thanks

**Comment by iDustbin** [comment]
Hi, sorry for my late response...
Actually im working on other project, please let me verify it until today evening... 
Thanks for all your help, im appreciated !

**Comment by Quentame** [comment]
Have you checked @iDustbin ?

**Comment by Quentame** [comment]
Tested with my calendar on global (working) and specific date (was not working).

Not returns `None` when no events between specific dates.
