### ISSUE TITLE
Still Alive

### ISSUE THREAD

**Issue by bickyb** [picklepete/pyicloud#223]
Hi, I wanted to see if this project is still alive.  I would like to use the library to find my iPhone.   I am not too much of a Python programmer, so I wanted to confirm that the code still works before I spend too long trying it.

**Comment by cjoshmartin** [comment]
It looks like it was last update 4 days ago

**Comment by Quentame** [comment]
Yep, I was added to the maintainers recently.

Using it in https://github.com/home-assistant/home-assistant personally.
