### ISSUE TITLE
PyiCloud Find-My-Friends Integration (solved)

### ISSUE THREAD

**Issue by gcobb321** [picklepete/pyicloud#231]
I created a customized version of PyiCloud that adds the Find-my-Friends service interface between PyiCloud and Apple's iCloud Web Services using code provided in several older issues and other web sites. This customized version has been in use by the Home Assistant iCloud3 custom component since September, 2019. (iCloud3 provides enhanced device tracking for Home Assistant users using the Find-my-Friends service to create a link between a non-2fa/non-2sa account and a 2fa account.)

Now that PyiCloud is back on an active maintenance path, I wanted to bring this code to your attention in case you want to add this service to PyiCloud. Upon review, you will find several new Classes that might be able to be easily incorporated into a new Find-my-Friends external service similar to the others provided by PyiCloud. Attached is the pyicloud_ic3.py code used by iCloud3. 

FYI - Links to the iCloud3 GitHub repository:
* iCloud3 GitHub Repository is [here](https://github.com/gcobb321/icloud3)
* iCloud3 documentation is [here](https://gcobb321.github.io/icloud3/#/)

Gary Cobb

[pyicloud_ic3.zip](https://github.com/picklepete/pyicloud/files/4238212/pyicloud_ic3.zip)

**Comment by Quentame** [comment]
Hi Gary !
Thanks for your attention about this repository, now live again ! 🍾 (Wouhooo)

I’ll take a look for sure at pyiCloud3 and integrate as much as I can in HA 😉
Sorry I didn’t have time to contact you for now, but be aware in one week and a half !

Can you propose a PR to this repo with the feature ?

Thanks !

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gcobb321** [comment]
1. Since the pyicloud version I modded was from last June, where is the latest version you are using that I can use for the PR. I put in other code that doesn’t apply that I don’t want to include. And I want to use it on iCloud3 to make sure it actually works.
2. What happens in 1-2/3 weeks? Didn’t understand.

**Comment by Quentame** [comment]
1. Master is more recent and nice for a PR
2. Will contact you by mail.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gcobb321** [comment]
I'll create a PR for base.py next week after I finish the latest update to iCloud3. The email I'm using on GitHub is geekstergary@gmail.com

**Comment by zzeleznick** [comment]
@gcobb321 - I already submitted a PR on #160, which you note in https://github.com/gcobb321/icloud3/blob/master/custom_components/icloud3/pyicloud_ic3.py#L14

Could you please clarify why you re-submitted my code as though you authored it?

<img width="1047" alt="Citogenesis | https:::xkcd com:978:" src="https://user-images.githubusercontent.com/5779832/78457917-9bbdc800-7662-11ea-8c40-f80582c3c07e.png">

**Comment by gcobb321** [comment]
I have thanked many people for code or inspiration that were involved in the original iCloud/HA development community as I wrote the iCloud3 device tracker program over the past few years.  During June and July, 2019, I cobbled together various pieces of code from several sources to get a functioning find-my-friends iCloud Location Service Access working after Apple forced 2fa notifications on everyone, shutting down the iCloud3 device tracker. I obviously reviewed the code in that pull request, along with many other sources, some python based, others not to get something working again. I put some pieces together creating an iCloud3 support program, pyicloud_ic3.py, which cites and thanks you and others.

PyiCloud.py looked like a dead project until a few months ago until Quentame resurrected it, started cleaning it up, dealing with various requests and problems and adding features, I thought adding the Find-my-Friends Service I was using in iCloud3 would be useful. My only intention in submitting the pull request was to provide this functionality to pyicloud.py since I had been using it without any problems in an ongoing project. It has been a long time since I worked with that code and didn't really think about where the various parts of it came from. 

I extracted the find-my-friends code from the pyicloud_ic3.py module and created the findmyfriends.py module in the same manner as the other support modules. It was strictly an oversite on my part that the credit for the code noted at the beginning of pyicloud_ic3.py was not added to the code I submitted. It was never my intent to take credit for code I did not develope. 

Please accept my apology for not citing you as one of the sources of the find-my-friends code I submitted.

If you wish, I will ask Quentame to delete my pull request and use the code you developed.

Gary Cobb
geekstergary@gmail.com

**Comment by zzeleznick** [comment]
Apology accepted.

Please close your pull request and I will work with @Quentame to merge the changes upstream.

**Comment by gcobb321** [comment]
Done. Also closed #265 which was meant to replace this one.
