### ISSUE TITLE
Set iPhone location 

### ISSUE THREAD

**Issue by aidanlam** [picklepete/pyicloud#236]
Hi there!

It would be pretty cool if there was a feature to update a devices location. I tried to see if this feature was included but could not find it.

Cheers!

**Comment by Quentame** [comment]
Hi there too !

What are you taking about ?
I don't get it, may you give us an exemple ?

If you want an updated location : 
- take your iPhone
- go to a pretty place nearby 
- go Python launch : `api_devces = iCloudService.devices` 
- devices data are stored and usable :wink: 

If you device is in pending state, you may refresh.

Procedure will change with #227

Exemple : https://github.com/home-assistant/core/blob/dev/homeassistant/components/icloud/account.py

**Comment by aidanlam** [comment]
Ah Im sorry I did not give enough detail. Allow me to elaborate. Not getting the iPhone location but spoofing it. 

`api.iphone.location()
>>> returns iPhone location 

api.iphone.set_location(40.741895, -73.989308)
api.iphone.location()
>>> returns new location
`

There is a old script which claims to be able to spoof location but I have yet to get it to work. https://github.com/alexisbosman/poof

**Comment by Quentame** [comment]
I don’t see why would it be useful.

As I told you before the only way to change a location is to move your device around.

This library can **get** devices state (location, battery ...) using the Find my iPhone API, but can’t **set** any device information.
Only devices can !

I don’t know why you want such thing but if you still do you can do it directly inside your app.

PS : a sure thing you can’t fake your iPhone location to play Pokémon on a good spot 🤣

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Quentame** [comment]
Not a issue, closing.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
