### ISSUE TITLE
"All Photos" album returning 0 photos

### ISSUE THREAD

**Issue by mdbraber** [picklepete/pyicloud#237]
Hi, 

I've created a simple login script that returns the number of photos in my "All Photos" album:

`print(len(api.photos.all))`

Weirdly enough this always return 0. If I try this for any other named album it works fine. Any idea what could be causing this or how to fix it? I've got 33,000+ photos in iCloud, could it be that the number of photos is too large to return?

**Comment by mdbraber** [comment]
Found the issue: I had once created a Smart Album called "All Photos" somewhere. Deleting that album fixed it!

**Comment by Quentame** [comment]
You’re welcome 😉 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Quentame** [comment]
You’re welcome 😂

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
