### ISSUE TITLE
pyicloud.exceptions.PyiCloudAPIResponseError: Invalid global session

### ISSUE THREAD

**Issue by subinjohnmathew** [picklepete/pyicloud#238]
I am a beginner, I was trying this and I am getting this error when trying to do.

> api.files.dir()

My code 
api = PyiCloudService('username', 'password')
PyiCloudService.authenticate(api)
print(api.files.dir())

**Comment by Quentame** [comment]
Hi @subinjohnmathew  !

We are an open source project, so don't forget to look at the source before creating an issue.
The `PyiCloudService` automatically authenticates you at the end of the class init : https://github.com/picklepete/pyicloud/blob/bd71ebf91676f7333aedae76f5978788f6b73c3b/pyicloud/base.py#L204

Plus, the authenticate function isn't static and don't need parameters : https://github.com/picklepete/pyicloud/blob/bd71ebf91676f7333aedae76f5978788f6b73c3b/pyicloud/base.py#L206

After doing this, I don't think your error will still exists.

See code exemple here : 
https://github.com/home-assistant/core/blob/445ef861c0dd36cbb8b85afc0bd7d47ed982ea96/homeassistant/components/icloud/account.py#L104-L124

Please tell me if it solves the issue.

**Comment by Quentame** [comment]
Not an issue + seems to work.

Closing.
