### ISSUE TITLE
PyiCloud Service Not Activated

### ISSUE THREAD

**Issue by saytinh** [picklepete/pyicloud#241]
I got issue after passed the login (api = PyiCloudService('user', 'pass'). The issue looks like this when I tried with api.devices. Please help me out as I'm just a newbie. Thanks

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyicloud/base.py", line 314, in devices
    service_root = self._get_webservice_url('findme')
  File "pyicloud/base.py", line 307, in _get_webservice_url
    ws_key
pyicloud.exceptions.PyiCloudServiceNotActivatedException: Webservice not available (findme)

**Comment by Quentame** [comment]
Please write why you close the issue so it can help new comers.

This Exception was built to indicate if the service is available.

Exemple : an iCloud account without device with “Find my iPhone” activated.

**Comment by saytinh** [comment]
This is my own fault as I used an icloud account that is not working on any iOS devices. After changing to another icloud account, it worked now.
