### ISSUE TITLE
https://pypi.org/project/pyicloud/0.9.6/#files

### ISSUE THREAD

**Issue by alteholz** [picklepete/pyicloud#253]
The tarfile pyicloud-0.9.6.tar.gz for version 0.9.6 at [1] does not seem to contain the directory pyicloud/services

  Thorsten

[1] https://pypi.org/project/pyicloud/0.9.6/#files

**Comment by Quentame** [comment]
Hi !

This has been fixed by #254 and released in [0.9.6.1](https://github.com/picklepete/pyicloud/releases/tag/0.9.6.1)

Thanks for beeing so responsive 😉 

Closing
