### ISSUE TITLE
Help building exe of icloudpd that use pyicloud

### ISSUE THREAD

**Issue by wes1993** [picklepete/pyicloud#262]
Hello,
can someone help me to make an exe of this project that use pyicloud dependecies?

https://github.com/ndbroadbent/icloud_photos_downloader

Thanks a lot
Stefano

**Comment by Quentame** [comment]
Hi !

You already opend an issue there ndbroadbent/icloud_photos_downloader#146 and people are responding.

Even if those repos are close, they are not the same.

Closing as not this repo.

**Comment by wes1993** [comment]
Thanks a lot for your reply!!!
:-D
