### ISSUE TITLE
Is there any way to unlock icloud account?

### ISSUE THREAD

**Issue by camelcdr** [picklepete/pyicloud#267]
Hi guys,
Somtimes my icloud account is locked for some reason, I need to unlock it by sending a email or answering two questions.
My question is if it could be done by pyicloud?
thanks a lot!

**Comment by Quentame** [comment]
Hi @camelcdr !
No it’s actually not possible to do that sorry.

Why are your iCloud account locked ?
Are you using the lob ?
What are your fetch frequency ?

Thanks.
PS: please respect the issue template.
