### ISSUE TITLE
PyiCloudAPIResponseException: Gone (410)

### ISSUE THREAD

**Issue by magus0219** [picklepete/pyicloud#269]
## The problem

I use pyiCloud to download all my photos (about 2600+), but after 1 hour(I think this is the threshold of session timeout) the program will throw PyiCloudAPIResponseException: Gone (410) and I can not easily go on.

## Environment

- pyiCloud release :  0.9.6.1 
- Last working pyiCloud release (if known): None
- Service causing this issue: photos
- Python version (`python -V`): 3.7.4
- Operating environment (project deps/Docker/Windows/etc.): MacOS 10.15.4

## Traceback/Error logs

```shell
Traceback (most recent call last):
  File "/Users/magus0219/Documents/PycharmProjects/icloud-photo-downloader/artascope/src/task/downloader.py", line 59, in download_file
    download = photo.download(timeout=30)
  File "/Users/magus0219/.local/share/virtualenvs/icloud-photo-downloader-ufb9U_1o/lib/python3.7/site-packages/pyicloud/services/photos.py", line 527, in download
    **kwargs
  File "/Users/magus0219/Documents/PycharmProjects/icloud-photo-downloader/artascope/src/patch/pyicloud.py", line 267, in get
    return self.request("GET", url, data=data, json=json, **kwargs)
  File "/Users/magus0219/.local/share/virtualenvs/icloud-photo-downloader-ufb9U_1o/lib/python3.7/site-packages/pyicloud/base.py", line 84, in request
    self._raise_error(response.status_code, response.reason)
  File "/Users/magus0219/.local/share/virtualenvs/icloud-photo-downloader-ufb9U_1o/lib/python3.7/site-packages/pyicloud/base.py", line 132, in _raise_error
    raise api_error

```

### How I login
```python
icloud_api = pyicloud.PyiCloudService(username, password, client_id=get_client_id())
```
* I use uuid to generate client id and persist it in redis to make sure they are same during later calling.
* I do not add cookie_directory and i am sure the tempfile module keep the cookie_direcotry the same.

### What i found
After reading the cookie content i know that:
1. First time PyiCloudService.authenticate() will plant the following cookies:
    - X-APPLE-WEBAUTH-HSA-LOGIN
    It seems PyiCloudService.send_verification_code() depend on this cookie or it will complain: Miss X-APPLE-WEBAUTH-HSA-LOGIN.
    - X_APPLE_WEB_KB
    Comments in the source code say it prevent Apple to send alerting email.
    - X-APPLE-WEBAUTH-LOGIN
    - X-APPLE-WEBAUTH-USER
    - X-APPLE-WEBAUTH-VALIDATE
    - X-APPLE-WEBAUTH-TOKEN
    Not sure their effect.

2. After i invoke PyiCloudService.validate_verification_code() successfully
    - X-APPLE-WEBAUTH-HSA-TRUST will replace X-APPLE-WEBAUTH-HSA-LOGIN
    - Cookies for each service added: Cloudkit/Documents/Mail/News/Notes/Photos/Safari/Sharing

### What i do to try to resolve (each step are independent experiment)
1. Do nothing but send request again(e.g. photo.download())
2. Load the same cookies from the cookie file followed by instantiating again(invoke authenticate automatically).
3. Remove X-APPLE-WEBAUTH-HSA-TRUST in the cookie file and  followed by instantiating again(invoke authenticate automatically) which result in X-APPLE-WEBAUTH-LOGIN but not X-APPLE-WEBAUTH-HSA-LOGIN
4. Remove all existed cookies except  X_APPLE_WEB_KB and do another login process.

Unfortunately I see PyiCloudAPIResponseException: Gone (410) each time...
I really can not understand why the 4th condition fails... the server side?

### A litter bit
By the way i use celery to leverage its retry function so basically i have a new PyiCloudService instance everytime. But i do not think it is the problem for they share same client id and cookie file.

I am crazy and help plz.

**Comment by magus0219** [comment]
I have resolved the problem myself and here it is:

When Gone Error happens, you should trigger query request like code in PhotoAblum.photos:
```python
@property
def photos(self):
    if self.direction == "DESCENDING":
        offset = len(self) - 1
    else:
        offset = 0

    while(True):
        url = ('%s/records/query?' % self.service._service_endpoint) + \
            urlencode(self.service.params)
        request = self.service.session.post(
            url,
            data=json.dumps(self._list_query_gen(
                offset, self.list_type, self.direction,
                self.query_filter)),
             headers={'Content-type': 'text/plain'}
        )
```
It is convenient to add your own method to do this query for func in this lib are not designed for this purpose.

And the key behind this is this query get download url of each photo and the url has timeout(not controlled by cookie)

**Comment by Quentame** [comment]
Thanks for solving this and post the solution.

I can try on my own to fix this but I have no photos in my iCloud.

Can you make a PR of a clean solution ?
