### ISSUE TITLE
Ability to set UUID - given Icloud Security changes

### ISSUE THREAD

**Issue by Ghawken** [picklepete/pyicloud#28]
Hi - thanks for this code.

Given Icloud Security changes though - any logon to icloud account results in a somewhat annoying email - per logon.

If the logon clientContext is set to a users existing device via deviceUDID the emails don't come anymore (presumably icloud know it is user authorised device and doesnt send them)

Is it possible to spoof this known client UDID, osVersion and ProductType to avoid these emails?

Thanks

```
        "clientContext":{
            "appName":"",,
            "buildVersion":"145",
            "deviceUDID":"xxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "inactiveTime":2147483647,
            "osVersion":"7.1.2",
            "personID":0,
            "productType":"iPad4,4"
```

Any chance to look at this as an option to stop the emails?

Glenn

**Comment by walchko** [comment]
agree, it is getting annoying with all the emails :)  If possible, would love some sort of fix for this ... thanks!

**Comment by coddingtonbear** [comment]
It'll probably take a while before this makes it close to the top of my queue; since both of you would like a fix sooner than later, could I convince one of you guys into posting a pull request?

**Comment by FiZiX** [comment]
It's not the same fix as recommended here but I think this should at least reduce the number of emails: https://github.com/picklepete/pyicloud/pull/41

**Comment by torarnv** [comment]
See #55

**Comment by torarnv** [comment]
After #55 was merged we now don't get a new e-mail on every second login, but since the cookie we store expires after 3 months, and I'm not sure if iCloud will send us an updated X-APPLE-WEB-KB cookie by that time to extend the session, we may still receive an email now and then. Having the ability to pass an existing `deviceUDID` may prevent this, so would maybe be worth looking into.

**Comment by torarnv** [comment]
@Ghawken Where did you see the `clientContext` being set? In the iCloud web client? Or sniffing one of the native clients?
