### ISSUE TITLE
PyiCloud

### ISSUE THREAD

**Issue by Guilholivier** [picklepete/pyicloud#284]
So i've just downloaded this app cuz rn im usin Linux, n im not used to much w that plataform as Macbook as do, so i dont have got a clue how am i doing wrong, cuz the appPyicloud do not show for, like ive just downloaded as i mentioned but i dont figured what am i have to do to use de app

**Comment by Quentame** [comment]
Hi !

1- Please follow the issue template
2- plz rite corectly dis is no izi 2 rid
3- pyiCloud can be used from the command line, otherwise it’s a library 
4- you should check on Google « how to install python app for command line », there is just one command

Thanks
