### ISSUE TITLE
Requirement is pinned for pyicloud 0.9.7: click>=6.0,<=7.1.1

### ISSUE THREAD

**Issue by MartinHjelmare** [picklepete/pyicloud#289]
## The problem

- This library supports an integration in Home Assistant.
- The upcoming pip resolver will be more strict in resolving package version conflicts:
http://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html#what-will-change
- To avoid future issues it would be good if this library would change its pinning to allow any higher version and just set a minimum version.

Thanks for your support of Home Assistant!

## Environment

- pyiCloud release with the issue (`pip show pyicloud`): 0.9.7
- Last working pyiCloud release (if known): 
- Service causing this issue: 
- Python version (`python -V`): 3.7.7
- Operating environment (project deps/Docker/Windows/etc.):  Ubuntu 18.04

## Traceback/Error logs

```shell
(home-assistant) x:~/Dev/home-assistant/home-assistant$ pip install -r requirements_all.txt
...
(home-assistant) x:~/Dev/home-assistant/home-assistant$ pipdeptree --reverse --packages click
...
click==7.1.1
...
  - pyicloud==0.9.7 [requires: click>=6.0,<=7.1.1]
...
```

**Comment by onkelbeh** [comment]
When will there be a fixed version? Can't compile anymore.

**Comment by onkelbeh** [comment]
still unusable with pyicloud-0.10.2...
