### ISSUE TITLE
iphone() doesn't always return your iPhone

### ISSUE THREAD

**Issue by walchko** [picklepete/pyicloud#29]
When I follow your example for getting all of my devices, my daughter's iTouch is the first device listed for some reason. Therefore, when I use your iphone method, her iTouch comes up. Is there a way you segment them by: iPod, iTouch, iPad, iPhone, etc and then iPhone would get all iPhones in my account?

```python
>>> for i in api.devices: print i
... 
iPod: Sammie's iTouch
iPhone 5s: Nina's iPhone
iPad Air 2: Star Lord
iPhone 5s: Sith-5S
iPhone 4s: Jedi-4S
iPad 2: Iron Man
iPad Air: Ninas iPad 
iPad 2: Ninas iPad
iPod: Mike iPod touch
MacBook Pro 13": Tardis
iPod: Kids's iPod touch
iPhone 4s: iPhone
iMac 21.5": Dalek
```

**Comment by coddingtonbear** [comment]
The `iphone` property is available only for backward compatibility with
earlier versions of this library; if you need to select a specific device
please use `api.devices`.

Cheers!

**Comment by walchko** [comment]
Thanks … great work by the way!
