### ISSUE TITLE
2FA cookies are now expiring after only 4 hours

### ISSUE THREAD

**Issue by leres** [picklepete/pyicloud#307]
## The problem

I doubt I'm the only one who's seeing this...

I have  a script that runs every 10 minutes. For several years I've only had to get a 2FA code from my phone once every 2 months. Starting on October 8th, 2020 this window seems to have closed to 4 hours.

## Environment

I'm running master/0efc4f4

## Traceback/Error logs

```shell

```

## Checklist

- [x] I've looked informations into the README.
- [x] I've looked informations into the pyiCloud's code.
- [x] I've looked informations in Google.

## Additional information
When I need to submit a 2FA code my phone does a pop-over asking if I want to allow the login but also sends an imessage with a code. The imessage code always works, the popover code is different and never works.

If I use a web browser to login to appleid.apple.com I only get the pop-over on my phone which works.

**Comment by nzapponi** [comment]
Fixed by #310

**Comment by leres** [comment]
The fix is greatly appreciated; I've had a session for 4 hours and 53 minutes and counting. Hopefully we're back to the 2FA every 60 days!

**Comment by nzapponi** [comment]
Yeah keep me posted. I successfully had it up and running for a few weeks. I was recently prompted for a 2FA code, but I suspect it was because I connected from a different country.

**Comment by VKSheridan** [comment]
Props to you nzapponi and team.  Your relentless effort is admirable!  Thank you!
