### ISSUE TITLE
Update pyicloud to use latest 2FA API

### ISSUE THREAD

**Issue by raman325** [picklepete/pyicloud#308]
## The request
It appears that `pyicloud` is using a legacy 2sv API, and as #307 indicates, Apple appears to have made a change that makes the current implementation unreliable because the 2sv token is expiring very quickly (or `pyicloud` is not storing the right cookie data). I found a JS implementation (https://github.com/MauriceConrad/iCloud-API) of the iCloud API that appears to use the latest 2FA implementation and would probably be more future proof. This implementation could serve as reference code for someone who knows JS to implement that logic in `pyicloud`.

## Environment

- pyiCloud version (`pip show pyicloud`): latest
- Python version (`python -V`): 3.8
- Operating environment (project deps/Docker/Windows/etc.): Docker

## Checklist

- [x] I've looked informations into the README.
- [x] I've looked informations into the pyiCloud's code.

**Comment by Quentame** [comment]
What is 2sv ? We should use 2FA.

**Comment by raman325** [comment]
you're right, I thought they were interchangeable but they aren't. 2FA is what we want to support.

**Comment by therealdandecker** [comment]
So where does this stand? Is the pyicloud library still being used if 2FA is not supported the same way? Is this ultimately an issue with the refresh token?

**Comment by blhoward2** [comment]
There is no refresh token. This isn't using an Apple API at all. It is web scraping the icloud.com website and storing the "remember me" session cookie.

**Comment by Quentame** [comment]
> There is no refresh token. This isn't using an Apple API at all. It is web scraping the icloud.com website and storing the "remember me" session cookie. This may be related to the deprecated nature of 2SA. Or it could be a permanent break if Apple (or its machine learning engine) has begun breaking this scraping method on purpose.

There is no web scraping, and yes, storing the "remember me" session cookie.
It simply uses https://www.icloud.com/ API requests to fetch data.
It is like we are an iCloud website user, but not fetching HTML, only JSON.
