### ISSUE TITLE
Github Actions

### ISSUE THREAD

**Issue by josuablejeru** [picklepete/pyicloud#329]
## Environment

- pyiCloud version (`pip show pyicloud`): 
- Python version (`python -V`): 
- Operating environment (project deps/Docker/Windows/etc.): 

## Checklist

- [ ] I've looked informations into the README.
- [x] I've looked informations into the pyiCloud's code.

## Additional information

I would like to add two Github Actions for running the test automatically and to publish the code to PiPy. I have seen in the Repo that you have some scripts already in place but the actions would give everybody a nice overview.

**Comment by MartinHjelmare** [comment]
GitHub actions for tests and PyPI publish are now in place. We can close here for now. :+1:
