### ISSUE TITLE
CalendarService error

### ISSUE THREAD

**Issue by dado3212** [picklepete/pyicloud#33]
When running a call to api.calendar.events(), I'm getting an error that 'CalendarService' object has no attribute 'get_possible_timezones', which is called on line 53 of calendar.py. Additionally, the function get_all_possible_timezones_of_local_machine returns an empty list.

**Comment by ShriramK** [comment]
Same issue

**Comment by zorangar** [comment]
Same issue :)

**Comment by torarnv** [comment]
This was fixed in version 0.6.2, please upgrade.
