### ISSUE TITLE
Upload files

### ISSUE THREAD

**Issue by dfranganillo** [picklepete/pyicloud#35]
Is it possible to upload a file with the current version? I cannot see any mention of "put" methods in the documentation.
If not, is is something being worked on? or it's just plainly impossible right now
Thanks.

**Comment by krzysztofantczak** [comment]
+1

**Comment by coddingtonbear** [comment]
Nope, that functionality does not exist in `pyicloud` at the moment, but if you find the time feel free to add that feature and send in a pull request!

Cheers,
Adam
