### ISSUE TITLE
App specific passwords

### ISSUE THREAD

**Issue by pliablepixels** [picklepete/pyicloud#36]
Hello, I'm curious why one needs the master password for iCloud and an app specific password does not work? Would you have any insights?

BTW, awesome stuff. I used your script to integrate with ZoneMinder (a linux ipcam DVR solution) to automatically start recording my cameras if my iPhone location is away from my home here http://www.zoneminder.com/forums/viewtopic.php?f=9&t=23026&p=87360#p87360

**Comment by arjunroychowdhury** [comment]
ah never mind - looked at the code - its a web scraper, so it makes sense that one needs the main password. Great work!
