### ISSUE TITLE
Stale location

### ISSUE THREAD

**Issue by arjunroychowdhury** [picklepete/pyicloud#37]
Hello, it looks like pyicloud is often returning a stale location when I query for location. The following situation results in a stale location almost always -- if you are not actively using your iPhone for a while and you are out of your LAN. To test, I logged into the iCloud interface on the web - that too shows the old location, but after a while updates to the new one. So my guess is the pyicloud is not waiting for a refresh (though I see you doing a refresh in the code). Do you know know to fix this?

**Comment by coddingtonbear** [comment]
Yep, check out this: https://github.com/coddingtonbear/django-location/blob/master/location/consumers/icloud.py#L131.

What you need to do, essentially, is request a new location until the response you receive's `locationFinished` key is `True`.

Cheers & good luck!

**Comment by arjunroychowdhury** [comment]
Thank you! So all I need to do is keep calling location till that flag is true.

Can you see if this is the right approach? I added a while loop before asking for lat/long

for rdev in  api.devices:
        dev = str(rdev)
        flog.write("Iterating device:%s\n" % dev);
        if my_dev_name in dev:
                flog.write("--- %s matches %s\n" % (dev,my_dev_name))
                while rdev.location()['locationFinished'] !=True:
                        pass
                latitude = float(rdev.location()['latitude'])
                longitude = float(rdev.location()['longitude'])

**Comment by coddingtonbear** [comment]
Yep, something like that should work just fine; the only thing I might suggest is changing it such that `rdev.location()` is called only once per loop -- each call of that method will send a request to iCloud and wait for a reply.

**Comment by arjunroychowdhury** [comment]
Great thank you.

**Comment by arjunroychowdhury** [comment]
Hello, a quick report: checking for the flag does not seem to work because I'm often getting a locationFinished=1 on first seek, but it is in fact, stale data. What seems to be working is this:

a) Query location once
b) Sleep for a while (I randomly selected 60s)
c) Query again. Now check for locationFinished. Repeat c) till  location Finished=1
d) Now get lat/long 

For example: here are my logs from my recent attempt. I was at office (18.3 miles from home) and drove to a nearby shop (around 0.6 miles away from office). I did a location seek and it still reported 18.3 miles from home, with Finished = 1. Snoozed for 60 seconds and did it again, and it worked

I'll double check this on my way from work to home later in the evening as the distance granularity is more.

Logs from my py app:

Phone Check log: Mon Mar 23 13:10:01 2015
I got location as: (lat) 39.108817, (long) -77.188001, Finished:1, Distance:18.334136 miles
Sleeping for 60 seconds to make sure its fresh...
AFTER SLEEP OF 60S: I got location as: (lat) 39.113135, (long) -77.199282, Finished:1, Distance:17.798161 miles
---location reported:lat:39.113135 long:-77.199282
----distance between points is 17.798161

**Comment by coddingtonbear** [comment]
Yeah -- it can definitely take a while -- if you check out https://github.com/coddingtonbear/django-location/blob/master/location/consumers/icloud.py#L131 you'll see that there are a few things that I check for in the data returned before counting it as an accurate location.  Although `locationFinished` is *often* good enough, you should probably also check the `isInaccurate` and `isOld` keys, too.

**Comment by arjunroychowdhury** [comment]
Thank you. So far I've been testing the method I outlined above: poll once, sleep for 60, poll again then check for locationFinished - its reliably working each time. If I land up into problems, I'll start exploring the other flags.
