### ISSUE TITLE
How we can get the address book of the user

### ISSUE THREAD

**Issue by Gaurav-Ambasta** [picklepete/pyicloud#39]
Hi , 

Can you please let me know how we can retrieve the address book of the user using pyicloud ??

Appreciate your support and waiting for your response.

Regards,
Gaurav

**Comment by torarnv** [comment]
You may use:

```
for contact in api.contacts.all():
    print contact.get('firstName'), contact.get('phones')
```

**Comment by torarnv** [comment]
See #60

**Comment by torarnv** [comment]
See #40
