### ISSUE TITLE
.location() suddenly throwing None

### ISSUE THREAD

**Issue by atomdog** [picklepete/pyicloud#403]
## Environment

- pyiCloud release with the issue (`pip show pyicloud`): 10.12
- Last working pyiCloud release (if known): This one
- Service causing this issue: Location
- Python version (`python -V`): 3.8.10
- Operating environment (project deps/Docker/Windows/etc.): 

## Traceback/Error logs

```shell

```

**Comment by JensDollenbacher** [comment]
For some devices (Watch 6, iPhone 13 in my case) .isLocating returns now "False" after Update to iOS 16.1 (WatchOS 9.1). Was reported "True" before the update. No location data available. Other devices (iPhone 12) report location as before.

**Comment by atomdog** [comment]
iPhone13 for me as well. Trying to find a workaround

**Comment by atomdog** [comment]
this randomly started working again despite neither the device or the code being patched. assume it is an apple thing 🤷
