### ISSUE TITLE
InsecurePlatformWarning:

### ISSUE THREAD

**Issue by ha11yb1and** [picklepete/pyicloud#43]
Hello! I get this warning every time I run the script

 A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
/usr/local/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/site-packages/requests-2.6.0-py2.7.egg/requests/packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)

**Comment by bschollnick** [comment]
I saw this too.  I solved it by updating, requests[security].

e.g. sudo pip install —upgrade requests[security]

		- Benjamin

**Comment by ha11yb1and** [comment]
Thank... but i now get this
InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.

**Comment by kspearrin** [comment]
I'm still getting these errors as well

**Comment by alanroche2015** [comment]
I found if you set self.session.verify = False in base.py to True and import SSL package you don't get the errors anymore.

**Comment by trusk89** [comment]
I've installed the requests[security] package, but I still get the warnings. And this triggers Apple to send me an email about logging in through an unsecured connection.

**Comment by torarnv** [comment]
Are there anyone still seeing these warnings with `pyicloud` version `0.7.2` or above?

**Comment by torarnv** [comment]
Closed due to inactivity, please comment if this still is an issue.
