### ISSUE TITLE
KeyError: 'dsid' when accessing file properties in iCloud Drive after successful authentication

### ISSUE THREAD

**Issue by kndrad** [picklepete/pyicloud#458]
## The problem

When trying to access files in the iCloud Drive using the PyiCloudService, a KeyError is raised for 'dsid' (Data Store ID). This occurs even after successful authentication and when the session is trusted. The error prevents access to the files in the iCloud Drive.

Specifically, the error occurs when trying to access `api.files[icloud_passwords_dir][filename].name`.

## Environment

- pyiCloud release with the issue (`pip show pyicloud`): Name: pyicloud
Version: 1.0.0
Summary: PyiCloud is a module which allows pythonistas to interact with iCloud webservices.
Home-page: https://github.com/picklepete/pyicloud
Author: 
Author-email: 
License: MIT
Location: /home/kndrad/projects/isync/.venv/lib/python3.12/site-packages
Requires: certifi, click, keyring, keyrings.alt, requests, tzlocal
Required-by: 
- Last working pyiCloud release (if known): 1.0.0
- Service causing this issue: iCloud Drive
- Python version (`python -V`): 3.12.5
- Operating environment (project deps/Docker/Windows/etc.): Arch Linux with Wayland (Sway)

## Traceback/Error logs

```shell

Traceback (most recent call last):
  File "main.py", line 89, in <module>
    print(api.files[icloud_passwords_dir][filename].name)
          ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/pyicloud/services/ubiquity.py", line 45, in __getitem__
    return self.root[key]
           ^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/pyicloud/services/ubiquity.py", line 19, in root
    self._root = self.get_node(0)
                 ^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/pyicloud/services/ubiquity.py", line 28, in get_node
    request = self.session.get(self.get_node_url(node_id))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/pyicloud/services/ubiquity.py", line 24, in get_node_url
    return self._node_url % (self.params["dsid"], variant, node_id)
                             ~~~~~~~~~~~^^^^^^^^
KeyError: 'dsid'

```

## Checklist

- [X] I've looked informations into the README.
- [X] I've looked informations into the pyiCloud's code.
- [X] I've looked informations in Google.

## Additional information
The `api.drive[icloud_passwords_dir].dir()` method works correctly and returns a list of files, but accessing individual file properties through `api.files[icloud_passwords_dir][filename].name` raises the KeyError.

**Comment by opfpqgoon** [comment]
Is the issue with the files or drive attributes of the api client?  api.files is for legacy ubiquity storage and likely isn't applicable to any modern apple account.  https://developer.apple.com/library/archive/technotes/tn2348/_index.html

Are you able to use the following?

api.drive[icloud_passwords_dir][filename].name

**Comment by kndrad** [comment]
Thank you so much for your quick and helpful response. You were absolutely correct, and I appreciate you pointing out the distinction between `api.files` and `api.drive`.

I've modified my code as you suggested, replacing `api.files` with `api.drive`, and I'm happy to report that it now works perfectly. 

I really appreciate your help in resolving this issue. Thank you again for your patience.
