### ISSUE TITLE
'com~apple~Notes' not showing up

### ISSUE THREAD

**Issue by briankaemingk** [picklepete/pyicloud#47]
Hi, thanks for this great work!  I can't seem to get access to iCloud notes.  

When I try....
    api.files.dir()

I get 
    ['com~apple~Preview', 'com~apple~TextEdit', 'com~apple~TextInput', 'com~apple~finder', 'com~apple~mail']

But no 'com~apple~Notes'.  Any ideas?  Thanks!

**Comment by torarnv** [comment]
Probably related to #51. I get the `com~apple~Notes` entry but `Documents` is empty, probably because they have been upgraded to using the `drivews` service.

```
>>> pprint(api.files['com~apple~Notes']['Documents'].dir())
[]
```

**Comment by torarnv** [comment]
Closing as duplicate.

**Comment by cabreramouzo** [comment]
Any idea why the Notes Document folder is empty? How to read my iCloud Notes?

**Comment by Quentame** [comment]
I don't know, maybe we should add its proper service to the library.
