### ISSUE TITLE
Allow session.verify

### ISSUE THREAD

**Issue by leres** [picklepete/pyicloud#52]
Could we please have some way to allow session.verify to be True? The attached patch is one possible way.

Hum... I'm getting "Attaching documents requires write permission to this repository. Try again with a PNG, GIF, or JPG." (that's pretty silly!)

Here's the patch inline..
<pre>
--- pyicloud-svn/base.py        2015-05-29 17:17:37.000000000 -0700
+++ pyicloud/base.py    2015-10-18 17:23:53.000000000 -0700
@@ -32,7 +32,7 @@
         pyicloud = PyiCloudService('username@apple.com', 'password')
         pyicloud.iphone.location()
     """
-    def __init__(self, apple_id, password, cookie_directory=None):
+    def __init__(self, apple_id, password, cookie_directory=None, verify=False):
         self.discovery = None
         self.client_id = str(uuid.uuid1()).upper()
         self.user = {'apple_id': apple_id, 'password': password}
@@ -57,7 +57,7 @@
             )
 
         self.session = requests.Session()
-        self.session.verify = False
+        self.session.verify = verify
         self.session.headers.update({
             'host': 'setup.icloud.com',
             'origin': self._home_endpoint,
</pre>

**Comment by jeremyjjr** [comment]
+1

**Comment by coddingtonbear** [comment]
Hey there @leres / @jeremyjjr -- could I convince you into filing a pull request for this?

**Comment by coddingtonbear** [comment]
Fixed via merging https://github.com/picklepete/pyicloud/pull/53; cheers!
