### ISSUE TITLE
Issues with cookielib after updating to 0.7.3

### ISSUE THREAD

**Issue by Xorso** [picklepete/pyicloud#62]
I am getting this error after upgrading to 0.7.3.

```
ImportError: No module named 'cookielib'
```
I checked pypi and the code and I am not sure where cookielib is to be installed from.

What am I missing?

**Comment by Xorso** [comment]
I found my problem. I was in a python3 virtual env. Is there any support for python3 with the library?

**Comment by coddingtonbear** [comment]
Not yet, but if you have a little time to assess the library for Python 3 support (and maybe post a PR or two fixing things up), it'd be much appreciated!

Cheers!
