### ISSUE TITLE
status fields

### ISSUE THREAD

**Issue by Bart274** [picklepete/pyicloud#74]
does anybody know the possible values of the deviceStatus and their meanings?
I would also love to know what other fields we can ask using the status function?

**Comment by torarnv** [comment]
Here are the values from the iCloud JavaScript:

```javascript
DEVICE_STATUS_ONLINE: 200,
DEVICE_STATUS_OFFLINE: 201,
DEVICE_STATUS_PENDING: 203,
DEVICE_STATUS_UNREGISTERED: 204,
DEVICE_STATUS_ERROR: 500,
```

You can inspect the full set of status fields using the device's (private) `content` property, and then pass the key, eg: `status(['deviceColor'])`:

`[u'features', u'maxMsgChar', u'darkWake', u'fmlyShare', u'deviceStatus', u'remoteLock', u'activationLocked', u'deviceClass', u'id', u'deviceModel', u'rawDeviceModel', u'passcodeLength', u'canWipeAfterLock', u'trackingInfo', u'location', u'msg', u'batteryLevel', u'remoteWipe', u'thisDevice', u'snd', u'prsId', u'wipeInProgress', u'lowPowerMode', u'lostModeEnabled', u'isLocating', u'lostModeCapable', u'mesg', u'name', u'batteryStatus', u'lockedTimestamp', u'lostTimestamp', u'locationCapable', u'deviceDisplayName', u'lostDevice', u'deviceColor', u'wipedTimestamp', u'modelDisplayName', u'locationEnabled', u'isMac', u'locFoundEnabled']`

**Comment by Bart274** [comment]
Thanks for the complete list! :)
