### ISSUE TITLE
first 1200 photos are fine, "Internal Server Error" on the rest

### ISSUE THREAD

**Issue by bherrmann7** [picklepete/pyicloud#88]
Any thoughts about this?
`
$ python
Python 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyicloud import PyiCloudService
>>> api = PyiCloudService('bob@jadn.com')
>>> print('You have %d photos' % (len(api.photos.all.photos)))
You have 1871 photos
>>> print api.photos.all.photos[700].filename
IMG_2013.JPG
>>> print api.photos.all.photos[1700].filename
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 242, in filename
    return self.data['details'].get('filename')
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 237, in data
    self._data = self.album._fetch_asset_data_for(self)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 205, in _fetch_asset_data_for
    self.service._fetch_asset_data_for(client_ids)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/services/photos.py", line 78, in _fetch_asset_data_for
    data=data
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 518, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pyicloud/base.py", line 99, in request
    raise api_error
pyicloud.exceptions.PyiCloudAPIResponseError: Internal Server Error (500)
>
`

**Comment by ShriramK** [comment]
@bherrmann7   
How often does this occur ? 
Have you tried accessing other items ? 
It could be a intermittent error

**Comment by bherrmann7** [comment]
The identical error happens ever time.

Months ago, I used the USB connector to connect the iphone to my computer as a hard drive.     I then copied and then deleted some photos from the phone.    I think this made "holes" in the photos metadata.    These phantom photos were showing up in icloud, but they were just blank.   I think accessing these was causing problems.

To work around this, I removed all the blanks using the photos app on the mac.    I then exported all images from the Photos app.   I then deleted all photos in icloud.      Would have been nice to test this theory before having deleted them all.    Ah well.

**Comment by torarnv** [comment]
I've seen the iCloud API return Internal Server Error (500) on requests made from the official iCloud web UI as well. They disappeared when the web UI finished "updating", whatever that means. I'm guessing there's some state server-side that needs to be regenerated or fixed. Not much we can do about it 😞
