### ISSUE TITLE
play_sound on family member's devices doesn't work? 

### ISSUE THREAD

**Issue by puntium** [picklepete/pyicloud#90]
I have a family account set up, so when I login with my icloud credentials, I see my family's devices. So far so good. But when I try to do a play_sound() with one of my family's device's device id, it doesn't work. I get an internal server error exception. It seems to work for my own devices just fine ("own" === my account is logged in as the icloud account on that device)

Curiously, if I use my family member's credentials to login to their account, I can play_sound() on their device just fine.

In the two cases, the device ID does appear to be different. When I'm logged in as myself, the device id of my family member's phone is much longer than the device ID for my own phone.

Also, other things like reading the family member's phone's location and battery seem to work just fine.

**Comment by torarnv** [comment]
Can you try the same use-case on icloud.com ?

**Comment by mrochford** [comment]
I validated that playing a sound via iCloud.com on a family device works. I too get a 500 internal error when trying to use play_sound() on device other than my own.

**Comment by chadj** [comment]
Pull request sent for a bug fix on this one.  Let me know what you think.

**Comment by mrochford** [comment]
@chadj  works awesome! Now just to get it merged!
