### ISSUE TITLE
using auth token instead of user/password

### ISSUE THREAD

**Issue by nirlandau** [picklepete/pyicloud#91]
Is it possible?

**Comment by torarnv** [comment]
Which auth token are you referring to? App specific passwords can not be used, see #92.

**Comment by nirlandau** [comment]
I am refering to general apple token. for example, when native apps (e.g. contacts) are connecting the server, a token is passing.
the token looks likes this:
8274655121:AQAAAVAABnYqmtl1ZiI/TQ+YUIfR763S9Iy+/j0=

**Comment by torarnv** [comment]
How would you retrieve this token? If you can use the token on icloud.com (set a cookie perhaps?) we can also use it.

**Comment by nirlandau** [comment]
for example, refer to https://github.com/horrorho/InflatableDonkey
you can download full icloud backup with it.

there it is mentioned that using tokens (DsPrsID:mmeAuthToken) is "Preferable for consecutive runs as repeated appleId/ password authentication over short periods may trip anti-flooding/ security controls."
so it gives you an option to obtain it (--token option).

these tokens work on icloud.com.
now i want to use this token with pyicloud.

**Comment by torarnv** [comment]
It seems both [InflatableDonkey](https://github.com/horrorho/InflatableDonkey) and [iloot](https://github.com/hackappcom/iloot) are using a reverse-engineered version of the CloudKit API, while we are using the APIs that the [icloud.com](icloud.com) website is using. The flow [here](https://github.com/horrorho/InflatableDonkey/blob/feccb6ae473763f281cbd2bcc6b2a25325f4ca44/CloudKit.md) doesn't match ours, we use a different endpoint that doesn't give us a `mmeAuthToken`.

> these tokens work on icloud.com

Just to clarify, are you basing that on the two projects mentioned already, or have you personally interacted with the icloud.com website using something else than your username and password?

**Comment by ifnull** [comment]
@torarnv does pyicloud save any token for later use or does it completely re-authenticate each time?

**Comment by nirlandau** [comment]
I am basing my answer on these two projects.
However, before iOS 9, I was able to use pyicloud with mmeAuthToken (witch I got from iloot)
has something changed?

**Comment by torarnv** [comment]
@ifnull A token is saved in the cookie file

@nirlandau Unless you can use the same `mmeAuthToken` to log into the current icloud.com, then `pyicloud` will not be able to use it either. Let me know if you can get it to work using icloud.com

**Comment by aress31** [comment]
This would be a super nice feature, up vote for me!

**Comment by Quentame** [comment]
It is not possible since we use iCloud.com authentication.

Same for App-specific password (see #161, #92 and #36), but we may implement 2FA (see #102).
