### ISSUE TITLE
get location in cosole DEVICE_ID

### ISSUE THREAD

**Issue by gine78** [picklepete/pyicloud#93]
hey,

i try the console command 

`icloud --username some@email.com --password AS3curePw! --locate --device anyUIDfromMYdevice`

The output that i became:

```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:789: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
```

The login is fine, i have become a email from apple tha anyone is using my icloud account with the webservice.

can anyont tell me my mistake? I only need the location of my iphone.

Thanks!

**Comment by coddingtonbear** [comment]
Those messages are warnings, not errors, and it is still sending the request whether or not it shows the message -- they're just letting you know that request we're making to iCloud is not verifying the certificate iCloud presented.

I'm not sure why that might be happening, though; glancing at the source, it does look like we do ask the `requests` library to verify the certificate.

**Comment by gine78** [comment]
i can deactivate the warnings - but, if i try to get the location with this command  

>`icloud --username some@email.com --password AS3curePw! --locate --device anyUIDfromMYdevice`

i dont become a result. 

if i try the `--llist` parameter, i get my devices. but i only need the location of my phone.

**Comment by stevenmcastano** [comment]
I'm seeing the same problem, I can get the just the location of a single device from the command line or from the python code itself.
