### ISSUE TITLE
Last Known Location

### ISSUE THREAD

**Issue by 123icebuggy** [picklepete/pyicloud#94]
Hey there!

Love the module it's really fantastic!

I was wondering if there is a way to update the location? Getting the last known location is brilliant, but is it possible to do a refresh? You can do such thing on the iCloud website, that way you can live track your phone.

Unfortunately I have not found a way to do this from within the module.

Thanks in advance

**Comment by coddingtonbear** [comment]
Yes -- this is very easy; that's actually what got me started on using this library, in fact.  Check out this section of the readme: https://github.com/picklepete/pyicloud#find-my-iphone

**Comment by 123icebuggy** [comment]
That doesn't mention refreshing it, only obtaining the last location. I would like to know how to refresh that information and get the iPhones current location

**Comment by coddingtonbear** [comment]
You may want to give it a shot, because if you try it experimentally, you'll discover that that's exactly what it does.

**Comment by 123icebuggy** [comment]
I tried getting my location 3 times, but it gives the last known and not current...

**Comment by the01** [comment]
What is the difference for you between 'last known' and 'current'? Because pyicloud only retrieves the information from the apple server. So if the server does not have your 'current' location, naturally neither does pyicloud..

**Comment by 123icebuggy** [comment]
Sorry for confusion, by current I don't mean what is on apple's servers. When you go to the find my phone site, upon clicking on your device it will fetch the latest location. Until I do this (or open the fmp app on my phone) pyicloud gives me the same coordinates

**Comment by coddingtonbear** [comment]
@123icebuggy -- just glancing at the output locally, it does appear that requesting location will cause the device to update its position:

```
>>> svc.devices[MY_DEVICE].location()
{u'timeStamp': 1471279639131, u'locationFinished': True, u'longitude': -122.6739292592953, u'positionType': u'GPS', u'locationType': None, u'latitude': 45.56513418913406, u'isOld': False, u'isInaccurate': False, u'horizontalAccuracy': 10.0}
>>> svc.devices[MY_DEVICE].location()
{u'timeStamp': 1471279639131, u'locationFinished': True, u'longitude': -122.6739292592953, u'positionType': u'GPS', u'locationType': None, u'latitude': 45.56513418913406, u'isOld': False, u'isInaccurate': False, u'horizontalAccuracy': 10.0}
>>> svc.devices[MY_DEVICE].location()
{u'timeStamp': 1471279672186, u'locationFinished': True, u'longitude': -122.6736591943751, u'positionType': u'GPS', u'locationType': None, u'latitude': 45.56539616551768, u'isOld': False, u'isInaccurate': False, u'horizontalAccuracy': 10.0}
>>> svc.devices[MY_DEVICE].location()
{u'timeStamp': 1471279678317, u'locationFinished': True, u'longitude': -122.6736591943751, u'positionType': u'GPS', u'locationType': None, u'latitude': 45.56539616551768, u'isOld': False, u'isInaccurate': False, u'horizontalAccuracy': 10.0}
```

Are you *sure* you're not seeing similar results?
