### ISSUE TITLE
battery drain

### ISSUE THREAD

**Issue by Bart274** [picklepete/pyicloud#98]
Is it me or is this component draining the battery of our devices than it used to do?

**Comment by stevenmcastano** [comment]
I'm using it to do fairly regular lookups for device location to do some proximity notifications for home, work, etc... and I haven't noticed any more drain than usual.

The only time there tends to be more battery drain then other times is if your GPS position is being figured by Cell. WiFi is much lower, GPS is the lowest battery drain, but if I'm indoors a lot without a WiFi connection and it has to use multiple cell towers and do the math to find it's position, it uses a little more battery.

That being said, it doesn't appear to be any more than it has been in the past.

**Comment by torarnv** [comment]
Hmm, I don't think `pyicloud` is at fault, or can do anything. If looking up the device position means a ping to the device, activating its radio, then if you do the lookup via `pyicloud` API or via icloud.com doesn't matter. A good idea if this can be observed (@stevenmcastano indicates it's not the case), is to rate-limit the lookups in the client of the  `pyicloud` API.
